# Generated by Django 2.0.7 on 2018-07-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_brand', models.TextField(verbose_name='PROCESSOR')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PC Price')),
            ],
        ),
    ]
